version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: employee-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: employee_db
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - employee-net

  app:
    build: .
    container_name: hrSys
    ports:
      - "8080:8080"
    environment:
      DB_HOST: "employee-db"
      DB_PORT: "5432"
      DB_USER: "admin"
      DB_PASSWORD: "admin123"
      DB_NAME: "employee_db"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - employee-net
    depends_on:
      - db
  migrate:
    image: migrate/migrate
    container_name: migrate
    volumes:
      - ./migrations:/migrations
    command: [ "-path", "/migrations", "-database", "postgres://admin:admin123@db:5432/employee_db?sslmode=disable", "up" ]
    depends_on:
      - db
    networks:
      - employee-net

networks:
  employee-net:
    driver: bridge
