version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: employee-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: employee_db
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - employee-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d employee_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: hrSys
    ports:
      - "8081:8080"
    working_dir: /app
    environment:
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_USER: "admin"
      DB_PASSWORD: "admin123"
      DB_NAME: "employee_db"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - employee-net

networks:
  employee-net:
    driver: bridge
